name: git_repo

on:
     push:
       branches:
         - main

jobs:
  demo:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: run
        run: |
          echo "${{ github.actor }} The checkout is completed"
           echo "Files in the repository:"
           ls -lrt

        
    
